### ISSUE TITLE
On DataLoader instance set { maxBatchSize: 100 }

### ISSUE THREAD

**Issue by codyfyi** [lifeomic/dynamodb-dataloader#12]
DynamoDB BatchGetItem restricts the batch size to 100 items. 

> If you request more than 100 items, BatchGetItem returns a ValidationException with the message "Too many items requested for the BatchGetItem call."

DataLoader has a `maxBatchSize` option that can be set to 100 to prevent a request from exceeding this limit.

- https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_BatchGetItem.html

**Comment by mdlavin** [comment]
Good point! That seems like a quick fix by adding the max batch size to the DataLoader constructor. Since you have a case to reproduce it, want to try to code a fix and submit a PR?
