### ISSUE TITLE
Ability to use Local and Global Secondary indexes

### ISSUE THREAD

**Issue by seriouscoderone** [lifeomic/dynamodb-dataloader#27]
Would be nice to have the ability to use Local or Global secondary indexes.

**Comment by mdlavin** [comment]
That's a great idea. If you have the time to put a PR up, I'd be happy to review it and get it merged.

**Comment by seriouscoderone** [comment]
Looked into it, unfortunately will not work. The DynamoDB `query` is the only way to access the LS/GS indexes. The query function is only designed to work within one partition.

https://forums.aws.amazon.com/thread.jspa?threadID=170405
```DynamoDB currently supports a single hash key for a Query operation. If you want to retrieve ranges for multiple hash keys you can use the Query API multiple times.```
